query appointments(
  $limit: Int
  $start: Int
  $startDate: String
  $endDate: String
) {
  appointments(
    start: $start
    where: { startDateTime_gte: $startDate, startDateTime_lte: $endDate }
    limit: $limit
    sort: "startDateTime:desc"
  ) {
    id
    startDateTime
    patient {
      id
      name
      mobile
    }
  }
}
