query appointments(
  $limit: Int
  $start: Int
  $startDate: String
  $endDate: String
) {
  appointments(
    start: $start
    where: { date_gte: $startDate, date_lte: $endDate }
    limit: $limit
    sort: "date:desc"
  ) {
    id
    date
    patient {
      name
      mobile
    }
  }
}
query appointmentFromId($id: String) {
  appointment(where: { id: $id }) {
    id
    date
    prescription {
      drug {
        name
      }
      frequency {
        frequency
        drugDuration
        drugDurationFor
        instructions
      }
    }
    vitalSigns {
      weight
      bp {
        bpSystolic
        bpDiastolic
      }
      temperature {
        temperature
      }
      pulse
      respRate
    }
    clinicalNotes {
      complaints
      observations
      diagnoses
      notes
    }
    patient {
      name
    }
    files {
      formats
    }
  }
}
