query patients($limit: Int, $start: Int) {
  patients(start: $start, limit: $limit, sort: "createdAt:desc") {
    id
    mobile
    name
    createdAt
    profile {
      id
      url
    }
    appointments {
      id
    }
  }
}

query getPatientNames {
  patients(sort: "name:asc") {
    id
    name
  }
}
