query patients($id: ID!) {
  patient(id: $id) {
    id
    mobile
    name
    address
    gender
    bloodGroup
    birthDate
    email
    pincode
    city
    profile {
      id
      url
    }
    appointments(sort: "createdAt:desc") {
      id
      clinicalNotes {
        diagnoses
        complaints
        observations
      }
      startDateTime
    }
  }
}
